# Generated by Django 3.1 on 2021-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time_created', models.DateField()),
                ('is_vis', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='topic_pic/')),
                ('time_created', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('is_vis', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('email', models.EmailField(max_length=254)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('is_superuser', models.BooleanField()),
            ],
        ),
    ]
