# Generated by Django 3.1 on 2021-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_comment_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.TextField(default='请输入你的标题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
