# Generated by Django 3.1 on 2021-10-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20211002_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='xxx', max_length=30),
        ),
        migrations.AddField(
            model_name='topic',
            name='creator',
            field=models.CharField(default='xxx', max_length=30),
        ),
    ]
