# Generated by Django 3.1 on 2021-10-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_picturewall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picturewall',
        ),
    ]
