# Generated by Django 3.1 on 2021-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_picturewall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picturewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateField(auto_created=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='topic_pic/')),
            ],
        ),
    ]
