# Generated by Django 3.1 on 2021-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_picturewall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='topic_pic/')),
                ('time_created', models.DateField(auto_now_add=True)),
                ('creator', models.CharField(default='admin', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('need_money', models.IntegerField(default=0)),
                ('have_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picturewall',
            name='time_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
