# Generated by Django 3.1 on 2021-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20211028_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='topic_pic/')),
                ('time_created', models.DateField(auto_now_add=True)),
                ('creator', models.CharField(default='admin', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('pay_min', models.IntegerField()),
                ('pay_max', models.IntegerField()),
                ('related_label', models.CharField(max_length=100)),
                ('where', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
