# Generated by Django 3.1 on 2021-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='herf',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
