# Generated by Django 3.1 on 2021-10-31 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_group_groupcomment_groupmessage_grouprealation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='time_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
